### ISSUE TITLE
Segfault w/bundler

### ISSUE THREAD

**Issue by nateberkopec** [rubinius/rubinius#3710]
https://travis-ci.org/puma/puma/jobs/177996892

1. What command did you run?

  I ran `bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}`

3. What behavior did you get instead?

```
Retrying fetcher due to error (2/4): NoMethodError undefined method `<' on nil:NilClass....
Retrying fetcher due to error (3/4): NoMethodError undefined method `<' on nil:NilClass...
Retrying fetcher due to error (4/4): ArgumentError TypedData object has already been freed.......
Fetching version metadata from https://rubygems.org/.*** Error in `ruby /home/travis/.rvm/gems/rbx-3/bin/bundle install --jobs=3 --retry=3 --path=vendor/bundle': double free or corruption (fasttop): 0x00007f93cc6686e0 ***
The Rubinius process is aborting with signal: SIGABRT
```

4. What version of Rubinius?

  Output of `rbx -v`: rubinius 3.69 (2.3.1 a57071c6 2016-11-17 3.8.0) [x86_64-linux-gnu]

5. What version of operating system?

  Ubuntu 14.04.5 LTS

7. How did you build your version of Rubinius?

  -[X] I used RVM.

8. Does this issue involve proprietary code?

  -[X] No, this issued doesn't involve proprietary code.

9. Are you able to help us debug the issue?

  -[X] Yes, I'm able to help debug, including running commands under lldb.

**Comment by brixen** [comment]
@nateberkopec thanks for reporting this issue. What version of Bundler are you running?

**Comment by nateberkopec** [comment]
Looks like it's 1.11.2

**Comment by brixen** [comment]
@nateberkopec ok, just to be super sure, you're using the Bundler that is pre-packaged with Rubinius and not installing a newer version, right?

**Comment by brixen** [comment]
@nateberkopec ahh, this looks suspect https://travis-ci.org/puma/puma/jobs/177996892#L152

**Comment by brixen** [comment]
@nateberkopec do you see this only on Travis or have you seen it locally where you can ensure that Bundler is not being upgraded?

**Comment by nateberkopec** [comment]
Oops, yeah. I was wondering why it was something that was only happening to us. 

So just to be clear - I must use the pre-packaged bundler version?

If that's all that needs to be done here and Bundler 1.13.6 not working is a "known issue", you can close.

**Comment by brixen** [comment]
@nateberkopec Bundler post 1.11.2 (ie post the version packaged with Rubinius) has a number of concurrency-related bugs. I'll definitely take a look at this, but I wanted to check that you were in fact using a newer version of Rubinius.

If I can determine that this is also a concurrency issue, I'll open [an issue like this one](https://github.com/bundler/bundler/issues/5142) for Bundler and close this.

Thanks again for reporting.

**Comment by mwpastore** [comment]
There's nothing like googling a bug and seeing it was solved/addressed 20 minutes ago! This issue report was quite timely. Thank you both.

**Comment by segiddins** [comment]
`ArgumentError: TypedData object has already been freed` seems to be coming from OpenSSL

```
    ArgumentError: TypedData object has already been freed
      /Users/segiddins/.rubies/rbx-3.69/gems/gems/rubysl-openssl-2.9/lib/openssl/ssl.rb:167:in `verify_certificate_identity'
      /Users/segiddins/.rubies/rbx-3.69/gems/gems/rubysl-openssl-2.9/lib/openssl/ssl.rb:317:in `post_connection_check'
      /Users/segiddins/.rubies/rbx-3.69/gems/gems/rubysl-net-http-2.0.4/lib/rubysl/net/http/http.rb:921:in `connect'
      /Users/segiddins/.rubies/rbx-3.69/gems/gems/rubysl-net-http-2.0.4/lib/rubysl/net/http/http.rb:862:in `do_start'
      /Users/segiddins/.rubies/rbx-3.69/gems/gems/rubysl-net-http-2.0.4/lib/rubysl/net/http/http.rb:857:in `start'
      /Users/segiddins/Development/OpenSource/bundler/lib/bundler/vendor/net/http/persistent.rb:700:in `start'
      /Users/segiddins/Development/OpenSource/bundler/lib/bundler/vendor/net/http/persistent.rb:631:in `connection_for'
      /Users/segiddins/Development/OpenSource/bundler/lib/bundler/vendor/net/http/persistent.rb:994:in `request'
      /Users/segiddins/Development/OpenSource/bundler/lib/bundler/fetcher/downloader.rb:50:in `request'
      /Users/segiddins/Development/OpenSource/bundler/lib/bundler/fetcher/downloader.rb:16:in `fetch'
      /Users/segiddins/Development/OpenSource/bundler/lib/bundler/fetcher/compact_index.rb:115:in `call'
      /Users/segiddins/Development/OpenSource/bundler/lib/bundler/compact_index_client/updater.rb:43:in `update'
      /Users/segiddins/.rubies/rbx-3.69/gems/gems/rubysl-tmpdir-2.0.1/lib/rubysl/tmpdir/tmpdir.rb:83:in `mktmpdir'
      /Users/segiddins/Development/OpenSource/bundler/lib/bundler/compact_index_client/updater.rb:30:in `update'
      /Users/segiddins/Development/OpenSource/bundler/lib/bundler/compact_index_client.rb:81:in `update'
      /Users/segiddins/Development/OpenSource/bundler/lib/bundler/compact_index_client.rb:97:in `update_info'
      /Users/segiddins/Development/OpenSource/bundler/lib/bundler/compact_index_client.rb:54:in `dependencies'
      core/proc.rb:20:in `call'
      /Users/segiddins/Development/OpenSource/bundler/lib/bundler/fetcher/compact_index.rb:86:in `compact_index_client'
      core/proc.rb:20:in `call'
      /Users/segiddins/Development/OpenSource/bundler/lib/bundler/worker.rb:65:in `apply_func'
      /Users/segiddins/Development/OpenSource/bundler/lib/bundler/worker.rb:60:in `process_queue'
      core/kernel.rb:585:in `loop'
      /Users/segiddins/Development/OpenSource/bundler/lib/bundler/worker.rb:57:in `process_queue'
      /Users/segiddins/Development/OpenSource/bundler/lib/bundler/worker.rb:29:in `initialize'
      core/proc.rb:20:in `call'
```

**Comment by brixen** [comment]
@segiddins the OpenSSL code is a C-ext extracted from MRI. It is very hard to know whether any of the OpenSSL code is intended to be thread-safe. There are some aspects of it that look like there was some attempt to make it thread-safe.

You'll note in the backtrace you listed that `bundler/lib/bundler/fetcher/compact_index.rb` is right there, just as in this issue https://github.com/bundler/bundler/issues/5142.

That code may well be sharing an OpenSSL structure along with the Set instance that it is surely sharing. I haven't dug into all that beyond the Set instance, but that's where I would suggest starting.

**Comment by segiddins** [comment]
This should now be fixed in Bundler master, although the bundler team is definitely interested in accepting contributions that improve performance under rbx!

**Comment by brixen** [comment]
Thanks @segiddins. So we can verify this, is there a Bundler release that includes the fix or is there an estimated time when there will be a release?

**Comment by segiddins** [comment]
Nope, no estimated time.

**Comment by abinoam** [comment]
Hi @brixen, 

Does bundler still have any problem with rubinius?
I've had some problems while ```bundle install``` at travis.
I came accross to this issue and saw the comments about problems with concurrency then I have limited the jobs number to see if it stop failing. Does it make any sense to do this way?
I'll keep an eye on it, but it happens that the builds are not failing anymore.
See the patch (awaiting review) at https://github.com/thoughtbot/factory_girl/pull/1035/commits/b7e1311df87d8d73fe356f4613064fc96175b716
See the passing build with it https://travis-ci.org/thoughtbot/factory_girl/jobs/278860657 (It doesn't fail at ```install``` step (bundle install).
See the previous failing build https://travis-ci.org/abinoam/factory_girl/builds/278787946

**Comment by brixen** [comment]
@abinoam I see that your spec run [is updating the Bundler version](https://travis-ci.org/thoughtbot/factory_girl/jobs/278860657#L750).

The only Bundler version that I know has not demonstrated concurrency bugs is the one preinstalled for Rubinius (ie version 1.11.2), so if your CI run is going to update Bundler, limiting the jobs to 1 is the only solution I know of until Bundler fixes the concurrency bugs.

**Comment by abinoam** [comment]
Thanks @brixen,

I'll see what approach the factory_girl maintainers prefer, not updating bundler or limiting job numbers.

**Comment by brixen** [comment]
General FYI to close out this issue, please see the current status of Bundler on Rubinius here https://github.com/rubinius/rubinius/issues/3781
